name: publish

on:
  push:
    branches: [ "master" ]
    paths: 
    - 'src/FluentFilter.MongoDB/FluentFilter.MongoDB.csproj'

jobs:
  publish-nuget:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build & Test & Pack
      run: |
        dotnet msbuild -target:src\\FluentFilter_MongoDB:YaccLexToolsGppg -target:src\\FluentFilter_MongoDB:YaccLexToolsGplex
        dotnet build --no-restore --configuration Release
        dotnet test --no-restore --no-build --configuration Release --verbosity normal
        dotnet pack --no-restore --configuration Release --verbosity normal
    - name: Publish  
      run: dotnet nuget push src/FluentFilter.MongoDB/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
