name: publish

on:
  push:
    branches: [ "master" ]
    paths: 
    - 'src/Elksoft.Converters/Elksoft.Converters.csproj'

jobs:
  publish-nuget:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          6.0.x
          7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build & Test & Pack
      run: |
        dotnet build --no-restore --configuration Release
        dotnet test --no-restore --no-build --configuration Release --verbosity normal
        dotnet pack --no-restore --configuration Release --verbosity normal
    - name: Publish  
      run: dotnet nuget push src/Elksoft.Converters/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
