name: verify

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Generate files
      run: dotnet msbuild -target:src\\FluentFilter_MongoDB:YaccLexToolsGppg -target:src\\FluentFilter_MongoDB:YaccLexToolsGplex
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-restore --no-build --configuration Release --verbosity normal
